---
title: "31 Read historical FB data"
author: "DHJ"
date: "25 2 2020"
output: 
  html_document:
    toc: true
    toc-float: true  
---

## 1. Libraries  
```{r}

library(R.matlab)     # read matlab files
library(dplyr)
library(purrr)
library(ggplot2)
library(viridis)
library(readr)
library(lubridate)

```

## 2. Test read from Matlab (Fantasy 2018)   
### Read  
```{r}

X <- R.matlab::readMat("Datasett/FB matlab/FA2018.mat")

# Check object
str(X, 1)
str(X$QC, 3)
str(X$cal, 3)
str(X$sensor, 2)

# Check each variable
# PCO2.TEMPERATURE and PCO2.SALINITY have only length 243858, the others 515151
nrows <- map_int(X$sensor, ~dim(.)[1])
data.frame(dimnames(X$sensor)[[1]], nrows)

# Make data frame
sel <- nrows == max(nrows)   # pick only variables with length 515151
FA2018 <- bind_cols(X[["sensor"]][sel])
names(FA2018) <- dimnames(X$sensor)[[1]][sel]

# Convert from matlab time
FA2018$Time <- as.POSIXct((FA2018$TIME - 719529)*86400, origin = "1970-01-01", tz = "UTC")

# Add QC for some vars
# Variable 16 has dimensions [1, 1:515151] so we pick only 1-15
QC <- bind_cols(X$QC[[1]][1:15])
names(QC) <- dimnames(X$QC[[1]])[[1]][1:15]
# Pick QC vars
# dimnames(X$QC[[1]])[[1]] %>% dput()
vars <- c("TEMP.IN", "TURB", "SAL", "TEMP", "FLU", "CDOM", "PCO2")
QC_foradd <- QC[vars]
names(QC_foradd) <- paste0(names(QC_foradd), "_QC")

# Add QC to FA2018
FA2018 <- bind_cols(FA2018, QC_foradd)

```

```{r}
names(FA2018)
```

### Test plots   
```{r}

FA2018 %>% 
  filter(LAT > 45 & LAT < 60) %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, LAT, color = factor(TEMP.IN_QC))) + 
  geom_point(alpha = 0.3)

FA2018 %>% 
  filter(TEMP.IN_QC == 1 & LAT > 45 & LAT < 60) %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, LAT, color = INLET.TEMPERATURE)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis()

FA2018 %>% 
  filter(SAL_QC == 1 & LAT > 45 & LAT < 60) %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, LAT, color = CTD.SALINITY)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis()

FA2018 %>% 
  filter(FLU_QC == 1 & LAT > 45 & LAT < 60) %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, LAT, color = FLU.FIELDCAL)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis()

```

## 3. Read Matlab files  2016-2017  

### Make FA2016 and FA2017  
Note: QC variables differ  
```{r}

#
# 2016
#
X <- R.matlab::readMat("Datasett/FB matlab/FA2016.mat")
# Length of each variable
nrows <- map_int(X$sensor, ~dim(.)[1])
# data.frame(dimnames(X$sensor)[[1]], nrows)
# Make data frame
sel <- nrows == max(nrows)   # pick only long variables (actually all are long in this case)
FA2016 <- bind_cols(X[["sensor"]][sel])
names(FA2016) <- dimnames(X$sensor)[[1]][sel]
# Convert from matlab time
FA2016$Time <- as.POSIXct((FA2016$TIME - 719529)*86400, origin = "1970-01-01", tz = "UTC")
# Add QC for some vars
# but only TURB and FLU has any 1's
QC <- bind_cols(X$QC[[1]][1:15])
names(QC) <- dimnames(X$QC[[1]])[[1]][1:15]
# map(QC, table)

# Pick QC vars
# dimnames(X$QC[[1]])[[1]] %>% dput()
vars <- c("TURB", "FLU")
QC_foradd <- QC[vars]
names(QC_foradd) <- paste0(names(QC_foradd), "_QC")
# Add QC to FA2016
FA2016 <- bind_cols(FA2016, QC_foradd)

#
# 2017
#
X <- R.matlab::readMat("Datasett/FB matlab/FA2017.mat")
# Length of each variable
nrows <- map_int(X$sensor, ~dim(.)[1])
# data.frame(dimnames(X$sensor)[[1]], nrows)
# Make data frame
sel <- nrows == max(nrows)   # pick only long variables (actually all are long in this case)
FA2017 <- bind_cols(X[["sensor"]][sel])
names(FA2017) <- dimnames(X$sensor)[[1]][sel]
# Convert from matlab time
FA2017$Time <- as.POSIXct((FA2017$TIME - 719529)*86400, origin = "1970-01-01", tz = "UTC")
# Add QC for some vars
# but only VAL, TURB and FLU has any 1's
QC <- bind_cols(X$QC[[1]][1:15])
names(QC) <- dimnames(X$QC[[1]])[[1]][1:15]
# map(QC, table)
# Pick QC vars
# dimnames(X$QC[[1]])[[1]] %>% dput()
vars <- c("VAL", "TURB", "FLU")
QC_foradd <- QC[vars]
names(QC_foradd) <- paste0(names(QC_foradd), "_QC")
# Add QC to FA2016
FA2017 <- bind_cols(FA2017, QC_foradd)

```

### Test plots of temperature  
```{r}
# names(FA2016)
# names(FA2017)
# names(FA2018)
# 
# xtabs(~TURB_QC + FLU_QC, FA2016)
# xtabs(~PUMP + FLU_QC + OBSTR, FA2016)

FA2016 %>% 
  filter(PUMP == 1 & OBSTR == 0 & LAT > 45 & LAT < 60) %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, LAT, color = TEMP.IN)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis()

FA2017 %>% 
  filter(PUMP == 1 & OBSTR == 0 & LAT > 45 & LAT < 60) %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, LAT, color = TEMP.IN)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis()

```

## 4. Read csv files 2002-2007  
Color Festival  

### Read all   
15 seconds or so
```{r, message=FALSE}

yrs <- 2002:2007
fn_pattern <- "K:/Avdeling/214-Oseanografi/DHJ/Data/Ferrybox csv/CF%i.csv"
fns <- sprintf(fn_pattern, yrs)

# Check
# read_csv(fns[1], n_max = 100)

# Don't actually know what the two FLU are, probably raw numbers and field-calibrated ones
names(fns) <- yrs
dat_list1 <- fns %>% map(read_csv, 
                         col_names = c("TIME", "Lon", "Lat", "Temp", 
                                       "Sal", "Flu1", "Flu"))   

dat1 <- bind_rows(dat_list1)

# Convert from matlab time
dat1$Time <- as.POSIXct((dat1$TIME - 719529)*86400, origin = "1970-01-01", tz = "UTC")

# Check variable names:  
# dat_list1 %>% map(names)

# dat_list[[8]] %>% head()

summary(dat1)

```

### Test plot
```{r}

dat1 %>% 
  sample_n(20000) %>%
  ggplot(aes(Time, Lat, color = Temp)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis(limits = c(-3, 25))

```

## 5. Read csv files 2008-2015 

### Read all  
Already cleaned  
```{r, message=FALSE}

yrs <- 2008:2015

fn_pattern <- "K:/Avdeling/214-Oseanografi/DHJ/Data/Fantasy_clean_csv/Fantasy_%i.csv"
fns <- sprintf(fn_pattern, yrs)

names(fns) <- yrs
dat_list2 <- fns %>% map(read_csv)

dat2 <- bind_rows(dat_list2)

# Check variable names:  
# dat_list2 %>% map(names)

# dat_list[[8]] %>% head()

```

### Test plot
```{r}

dat2 %>% 
  filter(Temp > (-4) & Temp <= 25) %>%
  sample_n(20000) %>%
  ggplot(aes(Time, Lat, color = Temp)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis(limits = c(-3, 25))

```

## 6. Prepare 2016-2018 data  

### 2016-2017  
```{r}

dat3 <- bind_rows(FA2016, FA2017) %>%
  filter(PUMP == 1 & OBSTR == 0 & LAT > 45 & LAT < 60) %>% 
  rename(Lat = LAT, Lon = LON, Temp = TEMP.IN, Sal = SAL) %>%
  mutate(d_seconds = (Time - lag(Time))/dseconds(1),
         d_lat = Lat - lag(Lat),
         Northbound = case_when(
           is.na(d_lat) ~ as.logical(NA),
           d_seconds > 300 ~ as.logical(NA),
           d_lat >= 0 ~ TRUE,
           d_lat < 0 ~ FALSE)
         ) %>%
  select(Time, Lat, Lon, Temp, Sal, Northbound)

```

### 2018  
```{r}

dat4 <- FA2018 %>%
  filter(TEMP.IN_QC == 1 & LAT > 45 & LAT < 60) %>% 
  rename(Lat = LAT, Lon = LON, Temp = INLET.TEMPERATURE, Sal = CTD.SALINITY) %>%
  mutate(Sal = ifelse(SAL_QC == 0, NA, Sal)) %>%
  mutate(d_seconds = (Time - lag(Time))/dseconds(1),
         d_lat = Lat - lag(Lat),
         Northbound = case_when(
           is.na(d_lat) ~ as.logical(NA),
           d_seconds > 300 ~ as.logical(NA),
           d_lat >= 0 ~ TRUE,
           d_lat < 0 ~ FALSE)
         ) %>%
  select(Time, Lat, Lon, Temp, Sal, Northbound)

```

## 7. Combine  
```{r}

dat <- bind_rows(dat1, dat2, dat3, dat4)

```

## 8. Check   

### Temperature, all latitudes  
```{r}

dat %>% 
  filter(Temp > (-4) & Temp <= 25) %>%
  sample_n(20000) %>%
  ggplot(aes(Time, Lat, color = Temp)) + 
  geom_point(alpha = 0.3) +
  scale_color_viridis(limits = c(-3, 25))

```

### Temp at ca Dk1  
```{r}
```

